spring:
   application: 
      name: DEFAULT-CONFIG

   datasource: 
      url: jdbc:mysql://localhost:3306/micro_yt 
      username: root
      password: mysql

   jpa:
      show-sql: true 
      hibernate: 
         ddl-auto: update
      
eureka:
   instance:
      client:
         serverUrl:
            defaultZone: http://localhost:8761/eureka/
